// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpqolorwaxtanwawxkgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcW9sb3J3YXh0YW53YXd4a2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODM0MDAsImV4cCI6MjA3MzI1OTQwMH0.16pCt_oBh-xkkCmA6JQaeqwTiB1KAZpkUUpxNsYPD4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});